# Generated by Django 5.0.1 on 2024-02-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt12',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
