# Generated by Django 5.0.1 on 2024-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0002_alter_cartaportedoc_txt12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestodoc',
            name='txt29',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
