# Generated by Django 5.0.1 on 2024-03-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiesto',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdocs.manifiestodoc'),
        ),
    ]
