# Generated by Django 5.0.1 on 2024-03-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0003_alter_manifiesto_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcuapassForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='documento',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='appdocs.manifiestodoc'),
            preserve_default=False,
        ),
    ]
