# Generated by Django 5.0.1 on 2024-03-04 14:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0004_ecuapassform_alter_manifiesto_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiestodoc',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='manifiestodoc',
            name='procedimiento',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifiestodoc',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
