# Generated by Django 5.0.1 on 2024-03-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0005_manifiestodoc_fecha_emision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiestodoc',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='manifiestodoc',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='manifiestodoc',
            name='usuario',
        ),
    ]
