# Generated by Django 5.0.1 on 2024-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0006_remove_manifiestodoc_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='procedimiento',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
