# Generated by Django 5.0.1 on 2024-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0007_declaracion_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt17_22',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
