# Generated by Django 5.0.1 on 2024-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0008_alter_cartaportedoc_txt17_22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt17_22',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt22',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
