# Generated by Django 5.0.1 on 2024-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0009_alter_cartaportedoc_txt17_22_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numeroId',
            field=models.CharField(max_length=30),
        ),
    ]
