# Generated by Django 5.0.1 on 2024-03-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0011_remove_cartaportedoc_txt20_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiestodoc',
            name='txt36',
        ),
        migrations.RemoveField(
            model_name='manifiestodoc',
            name='txt39',
        ),
    ]
